addons:
  certmanager:
    enabled: false
    # issuer_kind is a reference to the issuer for this certificate.
    # issuer_kind should be either `ClusterIssuer` or `Issuer`.
    # Please refer `IssuerRef` in https://github.com/jetstack/cert-manager/blob/master/pkg/apis/certmanager/v1alpha1/types_certificate.go
    # for more details about issuer_kind configuration.
    issuer_kind: ""
    issuer_name: ""

  hpa:
    enabled: false

  dns:
    enabled: true


kourier:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: true
